'use client';

import { useState } from 'react';

const NAVY = '#1B2A5E';
const PINK = '#E0006B';
const BOOKING_URL = 'https://street.co.uk/beta/platform/book-online/12c195c9-6dcc-45ed-adf9-1c5d7d4fd3c7/valuation/';

const faqs = [
  {
    q: 'Is the valuation really free?',
    a: 'Yes — completely free, with no strings attached. We will visit your property, give you an honest assessment based on real local data, and leave you with no obligation whatsoever. No pressure, no follow-up sales calls unless you want them.',
  },
  {
    q: 'How long does a valuation take?',
    a: 'Typically 30–45 minutes. We will walk through your property, ask a few questions, and give you a thorough, accurate figure — not a rushed number pulled from a portal.',
  },
  {
    q: 'Will I be pressured to sign with Johnsons?',
    a: 'Never. Our reputation is built on honest advice, not hard selling. If you decide to go with another agent, or not to sell at all, that is absolutely fine. We would rather give you a great experience and earn your trust than push you into something you are not ready for.',
  },
  {
    q: 'How do you calculate a valuation?',
    a: 'We use real sales data from your local area — comparable properties, recent sold prices, current market conditions across Evesham, Pershore, Broadway and The Lenches. Not automated estimates, not guesswork. A human who knows your street.',
  },
  {
    q: "What's the difference between your valuation and what I see on Rightmove or Zoopla?",
    a: 'Online estimates are generated by algorithms using broad data. They can be off by tens of thousands of pounds. Our valuation is done in person by someone who has sold homes on your road — that is a very different thing.',
  },
  {
    q: 'What if I am not ready to sell yet?',
    a: 'That is completely fine. Many people get a valuation simply to understand what they have. It helps you plan — whether that is 6 months away or 3 years. Knowing your number costs nothing and commits you to nothing.',
  },
  {
    q: 'How quickly can I get a valuation booked?',
    a: 'We typically have availability within a few days. Book online in under 60 seconds and we will confirm a time that suits you.',
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="border-b border-gray-100 cursor-pointer"
      onClick={() => setOpen(!open)}
    >
      <div className="flex items-center justify-between py-5 gap-4">
        <h3 className="font-semibold text-base md:text-lg" style={{ color: NAVY }}>{q}</h3>
        <span
          className="text-2xl font-light flex-shrink-0 transition-transform duration-300"
          style={{ color: PINK, transform: open ? 'rotate(45deg)' : 'rotate(0deg)' }}
        >
          +
        </span>
      </div>
      {open && (
        <p className="text-gray-600 leading-relaxed pb-5 text-sm md:text-base">{a}</p>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <main style={{ fontFamily: 'system-ui, -apple-system, sans-serif', color: '#111' }}>

      {/* Header */}
      <div className="py-20 px-6" style={{ background: NAVY }}>
        <div className="max-w-2xl mx-auto text-center">
          <p className="text-sm font-semibold uppercase tracking-widest mb-4" style={{ color: PINK }}>
            Got Questions?
          </p>
          <h1 className="text-white font-bold text-4xl md:text-5xl leading-tight mb-4">
            Everything You Need to Know
          </h1>
          <p className="text-white/70 text-lg">
            No jargon. No waffle. Just straight answers.
          </p>
        </div>
      </div>

      {/* FAQ list */}
      <div className="py-16 px-6 bg-white">
        <div className="max-w-2xl mx-auto">
          {faqs.map((item) => (
            <FAQItem key={item.q} q={item.q} a={item.a} />
          ))}
        </div>
      </div>

      {/* CTA */}
      <div className="py-16 px-6" style={{ background: '#F8F8F8' }}>
        <div className="max-w-xl mx-auto text-center">
          <h2 className="font-bold text-2xl md:text-3xl mb-4" style={{ color: NAVY }}>
            Ready to Find Out What Your Home Is Worth?
          </h2>
          <p className="text-gray-600 mb-8">
            Book your free valuation in under 60 seconds. No commitment, no pressure.
          </p>
          <a
            href={BOOKING_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-10 py-4 rounded-full font-bold text-white text-lg transition-all hover:scale-105 hover:shadow-xl"
            style={{ background: PINK, boxShadow: '0 4px 24px rgba(224,0,107,0.3)' }}
          >
            Book My Free Valuation →
          </a>
          <div className="mt-6">
            <a href="/" className="text-gray-400 text-sm hover:text-gray-600 transition-colors">
              ← Back to home
            </a>
          </div>
        </div>
      </div>

    </main>
  );
}
